# Generated by Django 5.0.1 on 2024-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
                ('routing_number', models.CharField(max_length=255)),
                ('swift_bic', models.CharField(max_length=255)),
            ],
        ),
    ]
